-- MySQL Script generated by MySQL Workbench
-- Wed Feb  2 22:35:42 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`item_shopping`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`item_shopping` (
  `item_id` INT(7) NOT NULL,
  `image` VARCHAR(53) NULL DEFAULT NULL,
  `name` VARCHAR(20) NULL DEFAULT NULL,
  `price` VARCHAR(5) NULL DEFAULT NULL,
  `weight` VARCHAR(6) NULL DEFAULT NULL,
  `qty` VARCHAR(3) NULL DEFAULT NULL,
  `category_name(FK)` VARCHAR(21) NULL DEFAULT NULL,
  PRIMARY KEY (`item_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT(11) NOT NULL,
  `Username` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `PhoneNumber` VARCHAR(11) NULL DEFAULT NULL,
  `Address` VARCHAR(60) NOT NULL,
  `City` VARCHAR(60) NOT NULL,
  `State` VARCHAR(60) NOT NULL,
  `Zip` VARCHAR(5) NOT NULL,
  `Password` VARCHAR(60) NOT NULL,
  `images` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`list_shopping`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`list_shopping` (
  `sl_id` INT(11) NOT NULL,
  `id` INT(20) NOT NULL,
  PRIMARY KEY (`sl_id`),
  INDEX `fk_user_id` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_user_id`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`itemlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`itemlist` (
  `itemlist_id` INT(10) UNSIGNED NOT NULL,
  `itemlist_qty` INT(11) NULL DEFAULT NULL,
  `subprice` DECIMAL(10,2) NOT NULL,
  `item_id` INT(100) NULL DEFAULT NULL,
  `sl_id` INT(50) NULL DEFAULT NULL,
  PRIMARY KEY (`itemlist_id`),
  INDEX `fk_item_id` (`item_id` ASC) VISIBLE,
  INDEX `fk_sl_id` (`sl_id` ASC) VISIBLE,
  CONSTRAINT `fk_item_id`
    FOREIGN KEY (`item_id`)
    REFERENCES `mydb`.`item_shopping` (`item_id`),
  CONSTRAINT `fk_sl_id`
    FOREIGN KEY (`sl_id`)
    REFERENCES `mydb`.`list_shopping` (`sl_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`list_ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`list_ingredient` (
  `il_id` INT(11) NOT NULL,
  `id` INT(20) NOT NULL,
  PRIMARY KEY (`il_id`),
  INDEX `fk_user_id` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_user_id`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`recipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recipe` (
  `recipe_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `steps` VARCHAR(45) NULL,
  `rating` VARCHAR(45) NULL,
  `image` VARCHAR(45) NULL,
  PRIMARY KEY (`recipe_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item_ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`item_ingredient` (
  `item_id` INT(7) NOT NULL,
  `name` VARCHAR(20) NULL DEFAULT NULL,
  `weight` VARCHAR(6) NULL DEFAULT NULL,
  `il_id` INT(11) NOT NULL,
  PRIMARY KEY (`item_id`),
  INDEX `fk_il_id_idx` (`il_id` ASC) VISIBLE,
  CONSTRAINT `fk_il_id`
    FOREIGN KEY (`il_id`)
    REFERENCES `mydb`.`list_ingredient` (`il_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`recipe_ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recipe_ingredient` (
  `item_id` INT(7) NOT NULL,
  `name` VARCHAR(20) NULL DEFAULT NULL,
  `weight` VARCHAR(6) NULL DEFAULT NULL,
  `recipe_id` INT(11) NOT NULL,
  PRIMARY KEY (`item_id`),
  INDEX `fk_recipe_id_idx` (`recipe_id` ASC) VISIBLE,
  CONSTRAINT `fk_recipe_id`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `mydb`.`recipe` (`recipe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
